web: npm run start
heroku config:set MONGODB_URI="mongodb+srv://userpedro:cocolisa@cluster0.ityz9.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

heroku config:set JWT_SECRET='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MDE1YTQ3M2I2MjZiNmJhMjM3NSIsImVtYWlsIjoianJpYmFsbG8yM0BnbWFpbC5jb20iLCJpYXQiOjE2NDc1OTU2MDIsImV4cCI6MTY0NzY4MjAwMn0.sKK1_impJ_WcKvCZHnGkM3vi70YcIyaOXhHpdSbWhRI'

